import dotenv from "dotenv";
dotenv.config();
export const {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  REFRESH_TOKEN,
  APP_URL,
  REFRESH_SECRET_EXPIRES_IN,
  JWT_SECRET_EXPIRES_IN,
  DEBUG_MODE,
  CAPTCHA_SECRET_KEY,
  EMAIL_PASSWORD,
  NODE_TLS_REJECT_UNAUTHORIZED,
  PUBLISHABLE_KEY,
  SECRET_KEY,
  FIREBASEAPIKEY,
  FIREBASEAUTHDOMAIN,
  FIREBASEPROJECTID,
  FIREBASESTORAGEBUCKET,
  FIREBASEMESSANGINGSENDERID,
  FIREBASEAPPID,
  FIREBASEMEASURMENTID
} = process.env;
